apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-container
          image: nginx:latest  # Replace this with the image you want to use for your container
      tolerations:
        - key: special
          operator: "Exists"  # You can set other operators if you have specific taint effects.

