apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: my-pdb
spec:
  selector:
    matchLabels:
      app: myapp  # Replace with the labels that match your pods
  minAvailable: 1        # Set the minimum number of available pods during disruptions
