apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: bhanuteja822-rolebinding
  namespace: nv1
subjects:
- kind: ServiceAccount
  name: bhanuteja822-serviceaccount
  namespace: nv1
roleRef:
  kind: Role
  name: bhanuteja822-role
  apiGroup: rbac.authorization.k8s.io