apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secretName }}
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  username: {{ .Values.username | b64enc }}
  password: {{ .Values.password | b64enc }}
  # Add other secret data here
